import type { Goal } from './types';

export const goals: Goal[] = [
  {
    type: "OKR",
    label: "Individual",
    title: "Ship Oxygen 2.0 dashboard to 100% of PW employees",
    subtitle: "Lead the design + research for the redesigned dashboard. Drive adoption past 80% WAU.",
    current: 64,
    target: 100,
    unit: "% rollout",
    percentage: 64,
    weight: 30,
    status: "On-track",
    state: "In Progress",
    barColor: "bg-green-500",
    krs: [
      { id: "KR 1", title: "Design system v2 components shipped (24 of 32)", percentage: 75 },
      { id: "KR 2", title: "Dashboard usability score ≥ 4.4 / 5", percentage: 88 },
      { id: "KR 3", title: "WAU adoption ≥ 80% by Q3", percentage: 90 },
    ],
  },
  {
    type: "OKR",
    label: "Functional",
    title: "Reduce design → engineering handoff time by 40%",
    subtitle: "From 4.2 days median to <2.5 days. Drive Figma → Storybook automation.",
    current: 3.4,
    target: 2.5,
    unit: "Days median",
    percentage: 42,
    weight: 20,
    status: "At-risk",
    state: "In Progress",
    barColor: "bg-yellow-500",
  },
  {
    type: "OKR",
    label: "Development",
    title: "Mentor 2 junior designers to mid-level promotion",
    subtitle: "Bi-weekly 1:1s; portfolio review; pair on 4+ shipped features each.",
    current: 1.6,
    target: 2,
    unit: "Promotion eligible",
    percentage: 80,
    weight: 15,
    status: "On-track",
    state: "In Progress",
    barColor: "bg-green-500",
  },
  {
    type: "OKR",
    label: "Functional",
    title: "Maintain CSAT for design partnership ≥ 4.5 / 5",
    subtitle: "Quarterly cross-functional partner survey of PMs and Eng Leads.",
    current: 4.6,
    target: 4.5,
    unit: "CSAT",
    percentage: 91,
    weight: 20,
    status: "On-track",
    state: "In Progress",
    barColor: "bg-green-500",
  },
  {
    type: "OKR",
    label: "Org",
    title: "Launch design-thinking workshop series across 5 BUs",
    subtitle: "Internal capability building. Quarterly cohort of 25 employees per BU.",
    current: 1,
    target: 5,
    unit: "BUs covered",
    percentage: 18,
    weight: 15,
    status: "Off-track",
    state: "In Progress",
    barColor: "bg-red-500",
  },
];
