import type {
  ApprovalGoal,
  CalibrationEmployee,
  CheckIn,
  DistributionBucket,
  GoalDetailData,
  OverviewTeamMember,
  ReporteeAssign,
  TeamMember,
} from "./types";

export const OVERVIEW_STATS = [
  {
    label: "REVIEWS TO COMPLETE",
    value: "6",
    sub: "2 of 8 done",
    valueColor: "text-blue-600",
  },
  {
    label: "GOALS PENDING APPROVAL",
    value: "3",
    sub: "submitted this week",
    valueColor: "text-orange-500",
  },
  {
    label: "SELF-REVIEWS SUBMITTED",
    value: "6 / 8",
    sub: "2 overdue",
    valueColor: "text-blue-600",
  },
  {
    label: "OFF-TRACK GOALS",
    value: "4",
    sub: "across 3 reportees",
    valueColor: "text-red-500",
  },
  {
    label: "TEAM AVG PROGRESS",
    value: "63%",
    sub: "8% vs Q4",
    valueColor: "text-green-600",
  },
];

export const OVERVIEW_TEAM_MEMBERS: OverviewTeamMember[] = [
  {
    id: "1",
    initials: "PM",
    name: "Pallavi Mahar",
    role: "Sr. Product Designer",
    tenure: "3.2y",
    goals: 5,
    progress: 64,
    self: "Done",
    review: "Not started",
    lastRating: "Exceeds",
    ratingColor: "bg-green-500",
    ratingText: "text-green-600",
    action: "Review",
  },
  {
    id: "2",
    initials: "KI",
    name: "Karthik Iyer",
    role: "Sr. Designer",
    tenure: "4.1y",
    goals: 5,
    progress: 78,
    self: "Done",
    review: "Done",
    lastRating: "Exceeds",
    ratingColor: "bg-green-500",
    ratingText: "text-green-600",
    action: "View",
  },
  {
    id: "3",
    initials: "MS",
    name: "Mohit Sinha",
    role: "Sr. Designer",
    tenure: "2y",
    goals: 4,
    progress: 52,
    self: "Done",
    review: "Not started",
    lastRating: "Meets",
    ratingColor: "bg-blue-500",
    ratingText: "text-blue-600",
    action: "Review",
  },
  {
    id: "4",
    initials: "RB",
    name: "Riya Banerjee",
    role: "Designer II",
    tenure: "1.8y",
    goals: 4,
    progress: 88,
    self: "Done",
    review: "Done",
    lastRating: "Exceeds",
    ratingColor: "bg-green-500",
    ratingText: "text-green-600",
    action: "View",
  },
  {
    id: "5",
    initials: "AB",
    name: "Aman Bhatt",
    role: "Designer II",
    tenure: "1.5y",
    goals: 4,
    progress: 45,
    self: "Pending",
    review: "Not started",
    lastRating: "Meets",
    ratingColor: "bg-blue-500",
    ratingText: "text-blue-600",
    action: "Nudge",
  },
  {
    id: "6",
    initials: "SD",
    name: "Shreya Das",
    role: "Designer I",
    tenure: "0.6y",
    goals: 4,
    progress: 71,
    self: "Done",
    review: "Not started",
    lastRating: null,
    ratingColor: "",
    ratingText: "",
    action: "Review",
  },
  {
    id: "7",
    initials: "VR",
    name: "Vikram Rao",
    role: "Designer II",
    tenure: "2.4y",
    goals: 4,
    progress: 30,
    self: "Overdue",
    review: "Not started",
    lastRating: "Below",
    ratingColor: "bg-yellow-500",
    ratingText: "text-yellow-600",
    action: "Nudge",
  },
];

export const APPROVAL_GOALS: ApprovalGoal[] = [
  {
    id: "a1",
    type: "OKR",
    employeeInitials: "PM",
    employeeName: "Pallavi Mahar",
    title: "Ship Oxygen 2.0 dashboard to 100% of PW employees",
    submittedAgo: "2 days ago",
    weightage: 30,
    checked: true,
  },
  {
    id: "a2",
    type: "OKR",
    employeeInitials: "PM",
    employeeName: "Pallavi Mahar",
    title: "Reduce design → eng handoff time by 40%",
    submittedAgo: "2 days ago",
    weightage: 20,
    checked: true,
  },
  {
    id: "a3",
    type: "OKR",
    employeeInitials: "KI",
    employeeName: "Karthik Iyer",
    warning: "Weightage exceeds 25% template",
    title: "Migrate auth service to v3 with zero-downtime cutover",
    submittedAgo: "1 day ago",
    weightage: 35,
    checked: false,
  },
  {
    id: "a4",
    type: "OKR",
    employeeInitials: "AB",
    employeeName: "Aman Bhatt",
    warning: "Edited after first approval",
    title: "Onboard 4 new engineers to platform team",
    submittedAgo: "4 hours ago",
    weightage: 25,
    checked: false,
  },
  {
    id: "a5",
    type: "OKR",
    employeeInitials: "MS",
    employeeName: "Mohit Sinha",
    title: "Maintain design CSAT ≥ 4.5",
    submittedAgo: "5 hours ago",
    weightage: 20,
    checked: false,
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "PW30004",
    initials: "S",
    name: "SHARON",
    designation: "ASS_ACD_DEF_FACULTY_CO-ORDINATION",
    goalCount: 1,
    avgProgress: 0,
    expanded: true,
    goals: [
      {
        id: "05a3190bfd",
        type: "OKR",
        title: "dd",
        progress: 0,
        status: "Off-track",
      },
    ],
  },
  {
    id: "PW-00008",
    initials: "SN",
    name: "SHINIL N",
    designation: "HR_TEST_DES",
    goalCount: 0,
    avgProgress: 0,
    expanded: false,
    goals: [],
  },
  {
    id: "PW30052",
    initials: "SS",
    name: "swapnil sadashiv raut",
    designation: "ACD_D&A_EXAMS_TEACHING",
    goalCount: 0,
    avgProgress: 0,
    expanded: false,
    goals: [],
  },
  {
    id: "PW30053",
    initials: "SS",
    name: "swapnil sadashiv raut",
    designation: "ACD_D&A_EXAMS_TEACHING",
    goalCount: 0,
    avgProgress: 0,
    expanded: false,
    goals: [],
  },
  {
    id: "PW30012",
    initials: "TT",
    name: "test test",
    designation: "PRF_ACD_DEF_OFF_TEACHING",
    goalCount: 0,
    avgProgress: 0,
    expanded: false,
    goals: [],
  },
];

export const TEAM_GOALS_GROUPS = [
  {
    employee: "PW30004",
    employee_name: "SHARON",
    initials: "S",
    designation: "ASS_ACD_DEF_FACULTY_CO-ORDINATION",
    image: null,
    goal_plan: "GP-0182",
    plan_status: "Approved",
    goal_count: 1,
    pending_count: 0,
    avg_progress: 0.0,
    goals: [
      {
        goal_key: "05a3190bfd",
        goal: "GOAL-26-03591",
        title: "dd",
        description: "SHARON",
        weightage: 100.0,
        methodology: "OKR",
        achievement: 0.0,
        expected_progress: 60.26,
        health: "off_track",
        health_label: "Off track",
        health_tone: "danger",
        is_mandatory: false,
        is_locked: false,
        edited_after_approval: false,
        key_results: [
          {
            goal_key: "9dd96d8d06",
            goal: null,
            title: "Complete faculty coordination workflow setup",
            weightage: 50.0,
            metric: null,
            target: 100.0,
            target_type: "",
            achievement: 0,
            goal_status: "Approved",
          },
          {
            goal_key: "9ed703b641",
            goal: null,
            title: "Conduct weekly faculty sync meetings",
            weightage: 50.0,
            metric: null,
            target: 10.0,
            target_type: "",
            achievement: 0,
            goal_status: "Approved",
          },
        ],
      },
    ],
  },
  {
    employee: "PW-00008",
    employee_name: "SHINIL N",
    initials: "SN",
    designation: "HR_TEST_DES",
    image: null,
    goal_plan: "GP-0164",
    plan_status: "Draft",
    goal_count: 0,
    pending_count: 0,
    avg_progress: 0.0,
    goals: [],
  },
  {
    employee: "PW30052",
    employee_name: "swapnil sadashiv raut",
    initials: "SS",
    designation: "ACD_D&A_EXAMS_TEACHING",
    image: null,
    goal_plan: "GP-0204",
    plan_status: "Draft",
    goal_count: 0,
    pending_count: 0,
    avg_progress: 0.0,
    goals: [],
  },
  {
    employee: "PW30053",
    employee_name: "swapnil sadashiv raut",
    initials: "SS",
    designation: "ACD_D&A_EXAMS_TEACHING",
    image: null,
    goal_plan: "GP-0205",
    plan_status: "Draft",
    goal_count: 0,
    pending_count: 0,
    avg_progress: 0.0,
    goals: [],
  },
  {
    employee: "PW30012",
    employee_name: "test test",
    initials: "TT",
    designation: "PRF_ACD_DEF_OFF_TEACHING",
    image: null,
    goal_plan: "GP-0189",
    plan_status: "Draft",
    goal_count: 0,
    pending_count: 0,
    avg_progress: 0.0,
    goals: [],
  },
];


export const GOAL_DETAIL: GoalDetailData = {
  id: "a1",
  type: "OKR",
  label: "Individual",
  status: "Submitted",
  approvalStatus: "Pending Approval",
  title: "Ship Oxygen 2.0 dashboard to 100% of PW employees",
  employeeInitials: "PM",
  employeeName: "Pallavi Mahar",
  designation: "Sr. Product Designer",
  submittedAgo: "2 days ago",
  weightage: 30,
  start: "1 Apr 2026",
  end: "31 Mar 2027",
  metric: "% rollout · target 100",
  alignedTo: "Alakh Pandey · Org OKR",
  contribution: "12% of parent",
  visibility: "Team",
  autoPull: "Jira · OXY-2.0",
  description:
    "Lead the design + research for the redesigned dashboard. Drive adoption past 80% WAU. Coordinate with PMM and CS for rollout comms. Quarterly progress reviews with Aditi.",
  keyResults: [
    {
      id: "KR 1",
      title: "Design system v2 components shipped (24 of 32)",
      target: 32,
    },
    { id: "KR 2", title: "Dashboard usability score ≥ 4.4 / 5", target: 4.4 },
    { id: "KR 3", title: "WAU adoption ≥ 80% by Q3", target: 80 },
  ],
  managerComment:
    "Looks good. Make sure KR3 has weekly check-ins — this is the riskiest one.",
  autoApprovesInDays: 2,
  auditLog:
    "Drafted 28 Apr · Submitted 30 Apr 09:14 · Edited 30 Apr 11:22 (added KR3) · Re-approval triggered",
};

export const CHECK_INS: CheckIn[] = [
  {
    id: "1",
    initials: "PM",
    name: "Pallavi Mahar",
    status: "Submitted",
    feeling: "4/5",
    hours: "42h",
    accomplished:
      "Shipped goals list + tree view. Calibration screen blocked on data model.",
    nextWeek:
      "Unblock data model with Karthik: build calibrator session screen.",
    blockers: 1,
  },
  {
    id: "2",
    initials: "KI",
    name: "Karthik Iyer",
    status: "Submitted",
    feeling: "5/5",
    hours: "45h",
    accomplished:
      "Auth v3 cutover successful — 0 incidents. Pair-programmed with Aman.",
    nextWeek: "Start on token system refactor.",
    blockers: 0,
  },
  {
    id: "3",
    initials: "MS",
    name: "Mohit Sinha",
    status: "Submitted",
    feeling: "3/5",
    hours: "40h",
    accomplished:
      "Recruitment redesign — 3 of 6 screens done. Blocked on PM availability.",
    nextWeek: "Sync with Neha on remaining 3 screens.",
    blockers: 2,
  },
  {
    id: "4",
    initials: "RB",
    name: "Riya Banerjee",
    status: "Submitted",
    feeling: "5/5",
    hours: "38h",
    accomplished: "Ran usability sessions with 8 students; v2 NPS at 72.",
    nextWeek: "Synthesize findings; share with team.",
    blockers: 0,
  },
  {
    id: "5",
    initials: "AB",
    name: "Aman Bhatt",
    status: "Missing",
    missingMessage:
      "No check-in submitted for week of 11 May · 4-day streak broken",
  },
  {
    id: "6",
    initials: "SD",
    name: "Shreya Das",
    status: "Submitted",
    feeling: "4/5",
    hours: "41h",
    accomplished: "Onboarding complete; first ticket merged.",
    nextWeek: "Pair with Mohit on Recruitment v2.",
    blockers: 0,
  },
  {
    id: "7",
    initials: "VR",
    name: "Vikram Rao",
    status: "Missing",
    missingMessage:
      "No check-in submitted for week of 11 May · 4-day streak broken",
  },
  {
    id: "8",
    initials: "PM",
    name: "Priya Menon",
    status: "Submitted",
    feeling: "3/5",
    hours: "39h",
    accomplished:
      "Q2 research plan signed off; recruiting blocked on agency contract.",
    nextWeek: "Push procurement to close contract this week.",
    blockers: 1,
  },
];

export const DISTRIBUTION: DistributionBucket[] = [
  { label: "Outstanding", target: 5, actual: 13, isRed: true },
  { label: "Exceeds", target: 15, actual: 25, isRed: true },
  { label: "Meets", target: 60, actual: 37, isRed: true },
  { label: "Below", target: 15, actual: 13, isRed: false },
  { label: "Unsatisfactory", target: 5, actual: 12, isRed: true },
];

export const CALIBRATION_EMPLOYEES: CalibrationEmployee[] = [
  {
    id: "1",
    initials: "PM",
    name: "Pallavi Mahar",
    role: "Sr. Product Designer",
    fy24: "Meets",
    fy25: "Exceeds",
    self: "Outstanding",
    peerAvg: "Exceeds",
    myProposal: "Exceeds",
    gridHighlight: [0, 2],
  },
  {
    id: "2",
    initials: "KI",
    name: "Karthik Iyer",
    role: "Sr. Designer",
    fy24: "Meets",
    fy25: "Exceeds",
    self: "Outstanding",
    peerAvg: "Outstanding",
    myProposal: "Exceeds",
    gridHighlight: [0, 2],
  },
  {
    id: "3",
    initials: "MS",
    name: "Mohit Sinha",
    role: "Sr. Designer",
    fy24: "Below",
    fy25: "Meets",
    self: "Exceeds",
    peerAvg: "Meets",
    myProposal: "Meets",
    gridHighlight: [1, 2],
  },
  {
    id: "4",
    initials: "RB",
    name: "Riya Banerjee",
    role: "Designer II",
    fy24: "Meets",
    fy25: "Exceeds",
    self: "Outstanding",
    peerAvg: "Outstanding",
    myProposal: "Outstanding",
    gridHighlight: [0, 2],
  },
  {
    id: "5",
    initials: "AB",
    name: "Aman Bhatt",
    role: "Designer II",
    fy24: "Below",
    fy25: "Meets",
    self: "-",
    peerAvg: "Meets",
    myProposal: "Meets",
    gridHighlight: [1, 2],
  },
  {
    id: "6",
    initials: "SD",
    name: "Shreya Das",
    role: "Designer I",
    fy24: "-",
    fy25: "-",
    self: "Outstanding",
    peerAvg: "Exceeds",
    myProposal: "Exceeds",
    gridHighlight: [2, 2],
  },
];

export const INITIAL_REPORTEES: ReporteeAssign[] = [
  {
    id: "1",
    initials: "PM",
    name: "Pallavi Mahar",
    subGoalTitle: "Adopt v2 in Oxygen dashboard (24 components)",
    weightage: 30,
    contribution: 35,
    status: "Submitted",
  },
  {
    id: "2",
    initials: "KI",
    name: "Karthik Iyer",
    subGoalTitle: "Token + theming infra in v2",
    weightage: 25,
    contribution: 25,
    status: "Approved",
  },
  {
    id: "3",
    initials: "MS",
    name: "Mohit Sinha",
    subGoalTitle: "Adopt v2 in Recruitment surface",
    weightage: 20,
    contribution: 20,
    status: "Submitted",
  },
  {
    id: "4",
    initials: "VR",
    name: "Vikram Rao",
    subGoalTitle: "Adopt v2 in LMS surface",
    weightage: 20,
    contribution: 15,
    status: "Draft",
  },
  {
    id: "5",
    initials: "RB",
    name: "Riya Banerjee",
    subGoalTitle: "Usability + telemetry for v2 components",
    weightage: 15,
    contribution: 10,
    status: "Submitted",
  },
];
