export type JobOpening = {
    name: string;
    owner: string;
    creation: string;
    modified: string;
    modified_by: string;
    docstatus: number;
    idx: number;
    job_title: string;
    designation: string;
    custom_how_the_vacancy_as_arisen: string;
    custom_replaced_with: string | null;
    status: string;
    custom_approved_on: string;
    posted_on: string;
    closes_on: string;
    closed_on: string | null;
    employment_type: string | null;
    location: string | null;
    staffing_plan: string;
    planned_vacancies: number;
    company: string;
    job_requisition: string | null;
    vacancies: number;
    custom_division: string | null;
    department: string | null;
    custom_recruiter: string | null;
    custom_hiring_manager: string | null;
    publish: number;
    route: string;
    publish_applications_received: number;
    job_application_route: string | null;
    custom_job_description_template: string;
    description: string;
    custom_reason_for_requesting: string;
    custom_sample_resume_link: string | null;
    currency: string;
    lower_range: number;
    upper_range: number;
    salary_per: string;
    publish_salary_range: number;
    custom__employee_type: string;
    custom_location: string | null;
    custom_work_experience: string;
    custom_salary: string | null;
    custom_preferred_notice_period: string;
  };
  
