export const ROUTES = {
  SEARCH_MEMBERS: "/webapp/search-members",
  TODO: "/webapp/todo-app",
  HR_PROCESS_MANDATORY: "/webapp/hr-process-mandatory",
  POLICIES_ENFORCED: "/webapp/policies-enforced",
  HELP_DESK: "/helpdesk/my-tickets",
  HELP_DESK_ADMIN: "/helpdesk",
  HELP_DESK_INTERNAL: "/webapp/helpdesk",
  EMPLOYEE_DOCUMENTS: "/webapp/employee-documents",
  EMPLOYEES_DIRECTORY_ADD: "/webapp/employees-directory/add-employee",
  EMPLOYEES_DIRECTORY_NEW_HIRES: "/webapp/employees-directory/new-hires",
  EMPLOYEES_DIRECTORY_INITIATE_ONBOARDING: "/webapp/employees-directory/initiate-onboarding",
  SEPARATION: "/webapp/flow-app/separation",
  SEPARATION_DASHBOARD: "/webapp/flow-app/separation-dashboard",
  PERFORMANCE_IMPROVEMENT: "/webapp/flow-app/performance-improvement",
};
