import type { CalibratorEmployee, DistributionItem, Rating, RatingOption } from "./types";

export const ratingOptions: RatingOption[] = [
  { label: "Outstanding", value: "Outstanding" },
  { label: "Exceeds", value: "Exceeds" },
  { label: "Meets", value: "Meets" },
  { label: "Below", value: "Below" },
];

export const distribution: DistributionItem[] = [
  { label: "Unsati", value: 8, color: "bg-blue-500", height: "h-2" },
  { label: "Below", value: 21, color: "bg-rose-500", height: "h-6" },
  { label: "Meets", value: 53, color: "bg-red-500", height: "h-14" },
  { label: "Exceed", value: 14, color: "bg-blue-500", height: "h-4" },
  { label: "Outsta", value: 4, color: "bg-blue-500", height: "h-1.5" },
];

export const employees: CalibratorEmployee[] = [
  {
    id: 1,
    initials: "PM",
    name: "Pallavi Mahar",
    detail: "Design · Oxygen · L4 · 3.2y",
    manager: "Rohit Khanna",
    prior: ["Meets", "Exceeds", "Exceeds"],
    self: "Outstanding",
    managerSuggested: "Outstanding",
    calibrated: "Exceeds",
    nineBox: [2, 0],
    override: true,
  },
  {
    id: 2,
    initials: "KI",
    name: "Karthik Iyer",
    detail: "Engineering · Platform · L4 · 4.1y",
    manager: "Rohit Khanna",
    prior: ["Meets", "Exceeds", "Outstanding"],
    self: "Outstanding",
    managerSuggested: "Outstanding",
    calibrated: "Outstanding",
    nineBox: [2, 0],
    flag: { label: "Promotion candidate", tone: "green" },
  },
  {
    id: 3,
    initials: "NP",
    name: "Neha Patel",
    detail: "Product · Oxygen · L4 · 5.2y",
    manager: "Sanjay Roy",
    prior: ["Exceeds", "Outstanding", "Exceeds"],
    self: "Outstanding",
    managerSuggested: "Exceeds",
    calibrated: "Exceeds",
    nineBox: [2, 1],
  },
  {
    id: 4,
    initials: "MS",
    name: "Mohit Sinha",
    detail: "Design · Recruit · L3 · 2.0y",
    manager: "Rohit Khanna",
    prior: ["Below", "Meets", "Meets"],
    self: "Meets",
    managerSuggested: "Meets",
    calibrated: "Meets",
    nineBox: [1, 1],
  },
  {
    id: 5,
    initials: "RB",
    name: "Riya Banerjee",
    detail: "Design · Oxygen · L2 · 1.8y",
    manager: "Rohit Khanna",
    prior: ["", "", "Exceeds"],
    self: "Outstanding",
    managerSuggested: "Outstanding",
    calibrated: "Outstanding",
    nineBox: [2, 0],
    flag: { label: "Hi-Po · early promo eligible", tone: "green" },
  },
  {
    id: 6,
    initials: "AB",
    name: "Aman Bhatt",
    detail: "Engineering · Web · L2 · 1.5y",
    manager: "Karthik Iyer",
    prior: ["", "", "Meets"],
    self: "Meets",
    managerSuggested: "Meets",
    calibrated: "Meets",
    nineBox: [1, 1],
  },
  {
    id: 7,
    initials: "SD",
    name: "Shreya Das",
    detail: "Design · Oxygen · L1 · 0.6y",
    manager: "Rohit Khanna",
    prior: ["", "", ""],
    self: "Outstanding",
    managerSuggested: "Exceeds",
    calibrated: "Exceeds",
    nineBox: [2, 0],
    flag: { label: "Probationary", tone: "amber" },
  },
  {
    id: 8,
    initials: "VR",
    name: "Vikram Rao",
    detail: "Design · LMS · L2 · 2.4y",
    manager: "Rohit Khanna",
    prior: ["Below", "Meets", "Below"],
    self: "Meets",
    managerSuggested: "Below",
    calibrated: "Meets",
    nineBox: [0, 1],
    flag: { label: "Manager raised - needs discussion", tone: "amber" },
    override: true,
  },
  {
    id: 9,
    initials: "PM",
    name: "Priya Menon",
    detail: "Research · L3 · 3.0y",
    manager: "Rohit Khanna",
    prior: ["Meets", "Exceeds", "Exceeds"],
    self: "Outstanding",
    managerSuggested: "Exceeds",
    calibrated: "Exceeds",
    nineBox: [2, 0],
  },
  {
    id: 10,
    initials: "SR",
    name: "Sanjay Roy",
    detail: "Product · Oxygen · L5 · 6.8y",
    manager: "Aditi Sharma",
    prior: ["Meets", "Exceeds", "Outstanding"],
    self: "Outstanding",
    managerSuggested: "Outstanding",
    calibrated: "Outstanding",
    nineBox: [2, 0],
  },
  {
    id: 11,
    initials: "TM",
    name: "Tarun Mishra",
    detail: "Engineering · Mobile · L3 · 2.7y",
    manager: "Karthik Iyer",
    prior: ["Below", "Meets", "Exceeds"],
    self: "Outstanding",
    managerSuggested: "Exceeds",
    calibrated: "Exceeds",
    nineBox: [2, 1],
  },
  {
    id: 12,
    initials: "DA",
    name: "Divya Agarwal",
    detail: "Product · Recruit · L3 · 2.2y",
    manager: "Sanjay Roy",
    prior: ["Meets", "Exceeds", "Meets"],
    self: "Exceeds",
    managerSuggested: "Exceeds",
    calibrated: "Meets",
    nineBox: [1, 1],
    flag: { label: "Inconsistent - yoy variance", tone: "amber" },
    override: true,
  },
];

export const ratingColorIndex: Record<Rating | "Unsatisfactory", number> = {
  Unsatisfactory: 0,
  Below: 4,
  Meets: 0,
  Exceeds: 2,
  Outstanding: 6,
};

export const ratingTextColor: Record<Rating, string> = {
  Outstanding: "text-emerald-400",
  Exceeds: "text-emerald-400",
  Meets: "text-sky-400",
  Below: "text-amber-400",
};

export const generatePastelColor = (index: number) => {
  const colors = [
    "bg-blue-100 text-blue-700 ring-blue-300",
    "bg-purple-100 text-purple-700 ring-purple-300",
    "bg-green-100 text-green-700 ring-green-300",
    "bg-pink-100 text-pink-700 ring-pink-300",
    "bg-yellow-100 text-yellow-700 ring-yellow-300",
    "bg-orange-100 text-orange-700 ring-orange-300",
    "bg-cyan-100 text-cyan-700 ring-cyan-300",
    "bg-red-100 text-red-700 ring-red-300",
  ];
  return colors[index % colors.length];
};
